Improved cr-script implementation
* The location of crclient executable is
  obtained dynamically
* The location was made to be set through environment
  variable

diff --git a/cr-script b/cr-script
--- a/cr-script
+++ b/cr-script
@@ -4,13 +4,50 @@
 # Usage: {script-name} <logout-parameter>
 #
 # Behaviour:
-#   Logs in when no parameter given
-#   Logs out if a single parameter is passed
+#   * Logs in when no parameter given
+#   * Logs out if a single parameter is passed
+#   * Requires the CR_CLIENT_LOCATION environment variable to be declared
+#     When not declared, asks for location and adds command to export CR_CLIENT_LOCATION to .bashrc
+#
+
+# Function to append data to .bashrc
+add_to_bashrc() {
+  if [ -z $1 ]
+  then
+    echo 1>&2 "FATAL! required parameter missing for core function"
+    exec 1>&- # remove binding of stdout to stderr
+  fi
+
+  echo -e $1 >> $HOME/.bashrc
+}
 
 username=171037-kaartic
 
+# If CR_CLIENT_LOCATION isn't defined get it's location
+# Further, add comand to export it to .bashrc
+if [ ! $CR_CLIENT_LOCATION ]
+then
+  echo "CR_CLIENT_LOCATION environment variable not defined."
+  while [ -z $location ] || [ ! -d $location ]
+  do
+    read -p "Enter directory in which crclient executable exists: " location
+    if [ ! -z $location ] && [ ! -d $location ]
+    then
+      echo "Directory $location doesn't exist. Please, try again."
+    fi
+  done
+
+  # Add command to export variable in future
+  add_to_bashrc "\n# Location of crclient executable"
+  add_to_bashrc "export CR_CLIENT_LOCATION=$location"
+  echo "Command to export CR_CLIENT_LOCATION has been added to your .bashrc file successfully!"
+
+  # Temporarily use locally defined variable
+  CR_CLIENT_LOCATION=$location
+fi
+
 # Change to folder containing executable as it's execution required it (!!!)
-cd /home/unique/Downloads/crclient
+cd $CR_CLIENT_LOCATION
 
 # Log in if no parameters are given
 if [ $# -eq 0 ]
